#!/bin/bash
# B9b.6 migration runner — plug-and-play.
#
# What this does:
#   1. Decodes the embedded migration script to lib/db/migrate-b9b6.mjs
#   2. Verifies it parses cleanly
#   3. Runs the migration against $DATABASE_URL
#
# All output stays in the terminal — script does NOT use `set -e` so a
# failure won't close the shell. Re-runnable: the migration itself is
# idempotent, so re-running this whole script is safe.

cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null

# Verify we're at the project root.
if [ ! -d lib/db ]; then
  echo "[fail] not at project root — lib/db/ not found in $(pwd)"
  echo "       Run from the workspace root (where lib/, artifacts/ live)."
  exit 1
fi

echo "=== 1. Writing lib/db/migrate-b9b6.mjs from embedded base64 ==="
base64 -d > lib/db/migrate-b9b6.mjs << 'B64_END'
Ly8gUGhhc2UgOWIuNiDigJQgREIgbWlncmF0aW9uCi8vCi8vIFNjaGVtYSBkZWx0YXM6Ci8vICAg
LSBwcm9zcGVjdHMuZ21haWxfbWVzc2FnZV9pZCBnbG9iYWwgVVEgY29uc3RyYWludCBSRU1PVkVE
LgovLyAgICAgICBCbG9ja2VkIHRoZSBjYW5vbmljYWwgcmUtZW5nYWdlbWVudCBjYXNlIHdoZXJl
IHRoZSBzYW1lCi8vICAgICAgIG91dGJvdW5kIG1lc3NhZ2UgYW5jaG9ycyBib3RoIGEgZG9jdHJp
bmUgcHJvc3BlY3QgYW5kIGFuCi8vICAgICAgIGFudGlfZ2hvc3RpbmcgcHJvc3BlY3QuCi8vICAg
LSBwcm9zcGVjdHMgKHVzZXJfaWQsIGdtYWlsX21lc3NhZ2VfaWQsIGFwcCkgdW5pcXVlSW5kZXgg
QURERUQuCi8vICAgICAgIFJlcGxhY2VtZW50IGNvbXBvc2l0ZSB1bmlxdWVuZXNzLiBTdHJpY3Rs
eSBtb3JlIHBlcm1pc3NpdmUKLy8gICAgICAgdGhhbiB0aGUgb2xkIGdsb2JhbCBVUSwgc28gbm8g
ZGF0YSBjbGVhbnVwIGlzIHJlcXVpcmVkLgovLwovLyBJZGVtcG90ZW50ICsgdHJhbnNhY3Rpb25h
bC4gUmUtcnVubmluZyBpcyBhIGNsZWFuIG5vLW9wLgovLwovLyBSdW4gZnJvbSBwcm9qZWN0IHJv
b3Q6ICBub2RlIGxpYi9kYi9taWdyYXRlLWI5YjYubWpzCi8vIFJlcXVpcmVzIERBVEFCQVNFX1VS
TCBpbiBlbnYuCgppbXBvcnQgcGcgZnJvbSAicGciOwpjb25zdCB7IFBvb2wgfSA9IHBnOwoKaWYg
KCFwcm9jZXNzLmVudi5EQVRBQkFTRV9VUkwpIHsKICBjb25zb2xlLmVycm9yKCJbZmFpbF0gREFU
QUJBU0VfVVJMIG11c3QgYmUgc2V0IGluIGVudiIpOwogIHByb2Nlc3MuZXhpdCgxKTsKfQoKY29u
c3QgcG9vbCA9IG5ldyBQb29sKHsgY29ubmVjdGlvblN0cmluZzogcHJvY2Vzcy5lbnYuREFUQUJB
U0VfVVJMIH0pOwoKYXN5bmMgZnVuY3Rpb24gZmluZEdsb2JhbFVxT25HbWFpbE1lc3NhZ2VJZChj
bGllbnQpIHsKICBjb25zdCByID0gYXdhaXQgY2xpZW50LnF1ZXJ5KGAKICAgIFNFTEVDVCBjb24u
Y29ubmFtZQogICAgRlJPTSBwZ19jb25zdHJhaW50IGNvbgogICAgSk9JTiBwZ19jbGFzcyByZWwg
T04gcmVsLm9pZCA9IGNvbi5jb25yZWxpZAogICAgSk9JTiBwZ19uYW1lc3BhY2UgbnNwIE9OIG5z
cC5vaWQgPSByZWwucmVsbmFtZXNwYWNlCiAgICBKT0lOIHBnX2F0dHJpYnV0ZSBhdHQKICAgICAg
T04gYXR0LmF0dHJlbGlkID0gcmVsLm9pZCBBTkQgYXR0LmF0dG51bSA9IEFOWShjb24uY29ua2V5
KQogICAgV0hFUkUgcmVsLnJlbG5hbWUgPSAncHJvc3BlY3RzJwogICAgICBBTkQgbnNwLm5zcG5h
bWUgPSBjdXJyZW50X3NjaGVtYSgpCiAgICAgIEFORCBjb24uY29udHlwZSA9ICd1JwogICAgICBB
TkQgYXR0LmF0dG5hbWUgPSAnZ21haWxfbWVzc2FnZV9pZCcKICAgICAgQU5EIGFycmF5X2xlbmd0
aChjb24uY29ua2V5LCAxKSA9IDEKICBgKTsKICByZXR1cm4gci5yb3dzLm1hcCgocm93KSA9PiBy
b3cuY29ubmFtZSk7Cn0KCmFzeW5jIGZ1bmN0aW9uIGluZGV4RXhpc3RzKGNsaWVudCwgaW5kZXhO
YW1lKSB7CiAgY29uc3QgciA9IGF3YWl0IGNsaWVudC5xdWVyeSgKICAgIGBTRUxFQ1QgMSBGUk9N
IHBnX2luZGV4ZXMKICAgICAgIFdIRVJFIHNjaGVtYW5hbWUgPSBjdXJyZW50X3NjaGVtYSgpCiAg
ICAgICAgIEFORCB0YWJsZW5hbWUgPSAncHJvc3BlY3RzJwogICAgICAgICBBTkQgaW5kZXhuYW1l
ID0gJDFgLAogICAgW2luZGV4TmFtZV0sCiAgKTsKICByZXR1cm4gci5yb3dDb3VudCA+IDA7Cn0K
CmFzeW5jIGZ1bmN0aW9uIG1haW4oKSB7CiAgY29uc3QgY2xpZW50ID0gYXdhaXQgcG9vbC5jb25u
ZWN0KCk7CiAgbGV0IGNoYW5nZWQgPSAwOwogIGxldCBza2lwcGVkID0gMDsKICB0cnkgewogICAg
Y29uc29sZS5sb2coIlN0YXJ0aW5nIFBoYXNlIDliLjYgbWlncmF0aW9uLi4uXG4iKTsKICAgIGF3
YWl0IGNsaWVudC5xdWVyeSgiQkVHSU4iKTsKCiAgICBjb25zdCB1cU5hbWVzID0gYXdhaXQgZmlu
ZEdsb2JhbFVxT25HbWFpbE1lc3NhZ2VJZChjbGllbnQpOwogICAgaWYgKHVxTmFtZXMubGVuZ3Ro
ID09PSAwKSB7CiAgICAgIGNvbnNvbGUubG9nKCJbc2tpcF0gbm8gZ2xvYmFsIFVRIG9uIHByb3Nw
ZWN0cy5nbWFpbF9tZXNzYWdlX2lkIik7CiAgICAgIHNraXBwZWQrKzsKICAgIH0gZWxzZSB7CiAg
ICAgIGZvciAoY29uc3QgbmFtZSBvZiB1cU5hbWVzKSB7CiAgICAgICAgYXdhaXQgY2xpZW50LnF1
ZXJ5KGBBTFRFUiBUQUJMRSBwcm9zcGVjdHMgRFJPUCBDT05TVFJBSU5UICIke25hbWV9ImApOwog
ICAgICAgIGNvbnNvbGUubG9nKGBbb2tdICAgZHJvcHBlZCBjb25zdHJhaW50ICIke25hbWV9IiBm
cm9tIHByb3NwZWN0c2ApOwogICAgICAgIGNoYW5nZWQrKzsKICAgICAgfQogICAgfQoKICAgIGlm
IChhd2FpdCBpbmRleEV4aXN0cyhjbGllbnQsICJ1cV9wcm9zcGVjdHNfdXNlcl9tZXNzYWdlX2Fw
cCIpKSB7CiAgICAgIGNvbnNvbGUubG9nKCJbc2tpcF0gdXFfcHJvc3BlY3RzX3VzZXJfbWVzc2Fn
ZV9hcHAgYWxyZWFkeSBleGlzdHMiKTsKICAgICAgc2tpcHBlZCsrOwogICAgfSBlbHNlIHsKICAg
ICAgYXdhaXQgY2xpZW50LnF1ZXJ5KAogICAgICAgIGBDUkVBVEUgVU5JUVVFIElOREVYIHVxX3By
b3NwZWN0c191c2VyX21lc3NhZ2VfYXBwCiAgICAgICAgICAgT04gcHJvc3BlY3RzICh1c2VyX2lk
LCBnbWFpbF9tZXNzYWdlX2lkLCBhcHApYCwKICAgICAgKTsKICAgICAgY29uc29sZS5sb2coCiAg
ICAgICAgIltva10gICBjcmVhdGVkIHVuaXF1ZUluZGV4IHVxX3Byb3NwZWN0c191c2VyX21lc3Nh
Z2VfYXBwKHVzZXJfaWQsIGdtYWlsX21lc3NhZ2VfaWQsIGFwcCkiLAogICAgICApOwogICAgICBj
aGFuZ2VkKys7CiAgICB9CgogICAgYXdhaXQgY2xpZW50LnF1ZXJ5KCJDT01NSVQiKTsKICAgIGNv
bnNvbGUubG9nKGBcbk1pZ3JhdGlvbiBjb21wbGV0ZS4gQ2hhbmdlZDogJHtjaGFuZ2VkfSwgU2tp
cHBlZDogJHtza2lwcGVkfWApOwoKICAgIGNvbnNvbGUubG9nKCJcbj09PSBWZXJpZnkgPT09Iik7
CiAgICBjb25zdCBzdGlsbEdsb2JhbFVxID0gYXdhaXQgZmluZEdsb2JhbFVxT25HbWFpbE1lc3Nh
Z2VJZChjbGllbnQpOwogICAgaWYgKHN0aWxsR2xvYmFsVXEubGVuZ3RoID4gMCkgewogICAgICBj
b25zb2xlLmVycm9yKGBbZmFpbF0gZ2xvYmFsIFVRIHN0aWxsIHByZXNlbnQ6ICR7c3RpbGxHbG9i
YWxVcS5qb2luKCIsICIpfWApOwogICAgICBwcm9jZXNzLmV4aXQoMSk7CiAgICB9CiAgICBjb25z
b2xlLmxvZygiW29rXSAgIG5vIGdsb2JhbCBVUSBvbiBwcm9zcGVjdHMuZ21haWxfbWVzc2FnZV9p
ZCIpOwoKICAgIGNvbnN0IGNvbXBvc2l0ZU9rID0gYXdhaXQgaW5kZXhFeGlzdHMoY2xpZW50LCAi
dXFfcHJvc3BlY3RzX3VzZXJfbWVzc2FnZV9hcHAiKTsKICAgIGlmICghY29tcG9zaXRlT2spIHsK
ICAgICAgY29uc29sZS5lcnJvcigiW2ZhaWxdIHVxX3Byb3NwZWN0c191c2VyX21lc3NhZ2VfYXBw
IG5vdCBmb3VuZCIpOwogICAgICBwcm9jZXNzLmV4aXQoMSk7CiAgICB9CiAgICBjb25zb2xlLmxv
ZygiW29rXSAgIHVxX3Byb3NwZWN0c191c2VyX21lc3NhZ2VfYXBwIHByZXNlbnQiKTsKCiAgICBj
b25zdCBhbGxJbmRleGVzID0gYXdhaXQgY2xpZW50LnF1ZXJ5KGAKICAgICAgU0VMRUNUIGluZGV4
bmFtZQogICAgICBGUk9NIHBnX2luZGV4ZXMKICAgICAgV0hFUkUgc2NoZW1hbmFtZSA9IGN1cnJl
bnRfc2NoZW1hKCkgQU5EIHRhYmxlbmFtZSA9ICdwcm9zcGVjdHMnCiAgICAgIE9SREVSIEJZIGlu
ZGV4bmFtZQogICAgYCk7CiAgICBjb25zb2xlLmxvZygiXG5BbGwgaW5kZXhlcyBvbiBwcm9zcGVj
dHM6Iik7CiAgICBmb3IgKGNvbnN0IHIgb2YgYWxsSW5kZXhlcy5yb3dzKSB7CiAgICAgIGNvbnNv
bGUubG9nKGAgICR7ci5pbmRleG5hbWV9YCk7CiAgICB9CiAgfSBjYXRjaCAoZXJyKSB7CiAgICBh
d2FpdCBjbGllbnQucXVlcnkoIlJPTExCQUNLIikuY2F0Y2goKCkgPT4ge30pOwogICAgY29uc29s
ZS5lcnJvcigiW2ZhaWxdIG1pZ3JhdGlvbiBlcnJvcjoiLCBlcnIpOwogICAgcHJvY2Vzcy5leGl0
KDEpOwogIH0gZmluYWxseSB7CiAgICBjbGllbnQucmVsZWFzZSgpOwogICAgYXdhaXQgcG9vbC5l
bmQoKTsKICB9Cn0KCm1haW4oKTsK
B64_END

if [ ! -s lib/db/migrate-b9b6.mjs ]; then
  echo "[fail] migration file is empty after decode"
  exit 1
fi
echo "    Wrote $(wc -c < lib/db/migrate-b9b6.mjs) bytes."

echo
echo "=== 2. Sanity-check the decoded script parses ==="
node --check lib/db/migrate-b9b6.mjs
if [ $? -ne 0 ]; then
  echo "[fail] decoded script has a syntax error — aborting before DB run"
  exit 1
fi
echo "    Parse OK."

echo
echo "=== 3. Running migration ==="
node lib/db/migrate-b9b6.mjs
RC=$?
echo
if [ $RC -eq 0 ]; then
  echo "=== DONE. Migration applied successfully. ==="
else
  echo "=== FAILED with exit code $RC — see error above. ==="
  echo "    Migration is transactional, so the DB was rolled back to its prior state."
fi
exit $RC
