// Bounce / non-delivery-report (NDR) classifier.
//
// Pure functions, no Gmail dependency, so they unit-test in isolation.
// gmailClient.classifyThreadInbound feeds each inbound thread message's
// From header, Subject, and snippet here and acts on the verdict.
//
// Design:
//   - A bounce is a delivery-failure message generated by a mail server,
//     not a human reply. Signals: a daemon sender (mailer-daemon,
//     postmaster), a delivery-status subject, a multipart report, or an
//     SMTP status code (4xx/5xx) paired with failure language.
//   - Per the operator decision, BOTH hard (5xx, recipient does not exist)
//     and soft (4xx, mailbox full / temporary) bounces auto-pause. The
//     classifier still reports which kind it found so the dashboard and the
//     weekly digest can label it.
//   - Vacation / out-of-office auto-replies come from the live recipient,
//     prove the address works, and must never be treated as bounces. They
//     fall through to the normal reply path.

export type BounceKind = "hard" | "soft";

export interface BounceVerdict {
  isBounce: boolean;
  kind?: BounceKind;
  // Short human-readable reason for logs / digest (e.g. "550 No such user").
  detail?: string;
}

const DAEMON_SENDER_PATTERNS: RegExp[] = [
  /\bmailer-daemon@/i,
  /\bpostmaster@/i,
  /\bmail\s*delivery\s*(system|subsystem)\b/i,
  /\bmaildaemon@/i,
  /\bno-?reply@.*(mail|smtp|delivery)/i,
];

const DSN_SUBJECT_PATTERNS: RegExp[] = [
  /undelivered\s+mail/i,
  /returned\s+mail/i,
  /delivery\s+status\s+notification/i,
  /delivery\s+(has\s+)?failed/i,
  /mail\s+delivery\s+failed/i,
  /failure\s+notice/i,
  /undeliverable/i,
  /message\s+not\s+delivered/i,
  /delivery\s+incomplete/i,
];

// Out-of-office / vacation auto-responders. These are NOT bounces.
const AUTOREPLY_SUBJECT_PATTERNS: RegExp[] = [
  /out\s+of\s+(the\s+)?office/i,
  /automatic\s+reply/i,
  /auto[\s-]?reply/i,
  /on\s+vacation/i,
  /away\s+from\s+(my\s+)?(the\s+)?(office|desk|email)/i,
  /annual\s+leave/i,
  /maternity\s+leave/i,
];

// Hard-failure language: the recipient does not exist or rejected delivery.
const HARD_FAIL_PATTERNS: RegExp[] = [
  /no\s+such\s+(user|recipient|address|mailbox)/i,
  /user\s+unknown/i,
  /recipient\s+(address\s+)?(rejected|not\s+found)/i,
  /address\s+(not\s+found|does\s+not\s+exist|rejected)/i,
  /mailbox\s+(unavailable|not\s+found|does\s+not\s+exist)/i,
  /does\s+not\s+exist/i,
  /unknown\s+recipient/i,
  /account\s+(has\s+been\s+)?disabled\s+or\s+discontinued/i,
  /domain\s+(not\s+found|does\s+not\s+exist)/i,
];

// Soft-failure language: temporary, likely to clear on retry.
const SOFT_FAIL_PATTERNS: RegExp[] = [
  /mailbox\s+(is\s+)?full/i,
  /over\s+quota/i,
  /quota\s+exceeded/i,
  /temporar(il)?y/i,
  /try\s+again\s+later/i,
  /greylist/i,
  /rate\s+limit/i,
  /deferred/i,
  /insufficient\s+(system\s+)?storage/i,
];

// SMTP status / enhanced status codes. 5xx and 5.x.x = hard; 4xx and 4.x.x = soft.
const HARD_CODE = /\b5\d{2}\b|\b5\.\d\.\d{1,3}\b/;
const SOFT_CODE = /\b4\d{2}\b|\b4\.\d\.\d{1,3}\b/;

function anyMatch(patterns: RegExp[], text: string): boolean {
  return patterns.some((p) => p.test(text));
}

function firstMatchText(patterns: RegExp[], text: string): string | undefined {
  for (const p of patterns) {
    const m = text.match(p);
    if (m) return m[0];
  }
  return undefined;
}

/**
 * Classify a single inbound thread message as a bounce or not.
 *
 * @param fromHeader  the raw From header of the inbound message
 * @param subject     the Subject header
 * @param snippet     Gmail's snippet of the message body (cheap, no body fetch)
 */
export function classifyBounce(
  fromHeader: string,
  subject: string,
  snippet: string,
): BounceVerdict {
  const from = (fromHeader || "").toLowerCase();
  const subj = subject || "";
  const snip = snippet || "";
  const haystack = `${subj}\n${snip}`;

  // Out-of-office from a real mailbox is never a bounce. Guard first so a
  // vacation message that happens to mention "delivery" does not misfire.
  const looksAutoReply = anyMatch(AUTOREPLY_SUBJECT_PATTERNS, subj);
  const fromDaemon = anyMatch(DAEMON_SENDER_PATTERNS, from);
  if (looksAutoReply && !fromDaemon) {
    return { isBounce: false };
  }

  const dsnSubject = anyMatch(DSN_SUBJECT_PATTERNS, subj);
  const hasHardCode = HARD_CODE.test(haystack);
  const hasSoftCode = SOFT_CODE.test(haystack);
  const hardLang = anyMatch(HARD_FAIL_PATTERNS, haystack);
  const softLang = anyMatch(SOFT_FAIL_PATTERNS, haystack);

  const isBounce =
    fromDaemon ||
    dsnSubject ||
    ((hasHardCode || hasSoftCode) && (hardLang || softLang));

  if (!isBounce) return { isBounce: false };

  // Resolve hard vs soft. Hard wins when present, since a 5xx / "no such
  // user" means the address will not deliver on retry.
  let kind: BounceKind = "soft";
  if (hasHardCode || hardLang) kind = "hard";
  else if (hasSoftCode || softLang) kind = "soft";
  else kind = "hard"; // daemon/DSN with no parseable code: treat as hard so it pauses and surfaces.

  const detail =
    firstMatchText(HARD_FAIL_PATTERNS, haystack) ||
    firstMatchText(SOFT_FAIL_PATTERNS, haystack) ||
    firstMatchText([HARD_CODE, SOFT_CODE], haystack) ||
    (dsnSubject ? firstMatchText(DSN_SUBJECT_PATTERNS, subj) : undefined) ||
    (fromDaemon ? "mail delivery system" : undefined);

  return { isBounce: true, kind, detail };
}
