/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns server health status
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard statistics */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prospects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get prospects grouped by vertical and date */
        get: operations["getProspects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/followups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get follow-ups with optional status filter */
        get: operations["getFollowups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Gmail sync */
        post: operations["triggerSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process due follow-ups */
        post: operations["triggerProcess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue follow-ups for specific prospects */
        post: operations["queueFollowups"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queue-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue follow-ups for a batch of prospects */
        post: operations["queueBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/sent-emails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch recent sent emails from Gmail with detection analysis */
        get: operations["getSentEmails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/thread/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch full thread details */
        get: operations["getThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Google OAuth URL to connect a Gmail account */
        get: operations["startGmailAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List connected Gmail accounts */
        get: operations["getGmailAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect a Gmail account */
        delete: operations["disconnectGmailAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gmail/accounts/{id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update follow-up settings for an account */
        put: operations["updateAccountSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel queued follow-ups */
        post: operations["cancelFollowups"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prospect/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause follow-ups for a specific prospect */
        post: operations["pauseProspect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prospect/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume follow-ups for a specific prospect */
        post: operations["resumeProspect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaign/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get campaign status */
        get: operations["getCampaignStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaign/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue next follow-ups for a specific campaign type */
        post: operations["queueCampaignFollowups"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaign/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch test follow-up campaign */
        post: operations["launchCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaign/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop follow-up campaign */
        post: operations["stopCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            status: string;
        };
        Stats: {
            total_sent: number;
            unreplied: number;
            replied: number;
            queued_followups: number;
            sent_followups: number;
        };
        Prospect: {
            id: number;
            gmail_message_id: string;
            gmail_thread_id: string;
            prospect_name: string;
            company: string;
            email: string;
            vertical: string;
            product: string;
            subject: string;
            original_body_summary: string;
            batch_label: string;
            sent_at: string;
            replied: number;
            replied_at?: string | null;
            followup_paused?: boolean;
            is_test_campaign?: boolean;
            max_followups?: number;
            followup_1_status?: string | null;
            followup_1_scheduled?: string | null;
            followup_2_status?: string | null;
            followup_2_scheduled?: string | null;
            followup_3_status?: string | null;
            followup_3_scheduled?: string | null;
        };
        ProspectGroup: {
            label: string;
            vertical: string;
            sent_date: string;
            prospects: components["schemas"]["Prospect"][];
            total: number;
            unreplied: number;
            replied: number;
        };
        Followup: {
            id: number;
            prospect_id: number;
            stage: number;
            status: string;
            scheduled_at: string;
            generated_body?: string | null;
            generated_subject?: string | null;
            sent_at?: string | null;
            gmail_message_id?: string | null;
            error_message?: string | null;
            created_at: string;
            prospect_name: string;
            company: string;
            email: string;
            vertical: string;
            original_subject: string;
            batch_label?: string | null;
            is_test_campaign?: boolean;
            followup_paused?: boolean;
            replied?: number;
            max_followups?: number;
        };
        SyncResult: {
            synced: number;
            repliesDetected: number;
        };
        ProcessResult: {
            processed: number;
            sent: number;
            failed: number;
        };
        QueueRequest: {
            prospect_ids: number[];
            stage: number;
        };
        QueueBatchRequest: {
            vertical?: string;
            sent_date?: string;
            stage: number;
            exclude_ids?: number[];
        };
        CancelRequest: {
            followup_ids: number[];
        };
        QueueResult: {
            queued: number;
            scheduled_range: {
                earliest?: string;
                latest?: string;
            };
        };
        SentEmailDetection: {
            wouldBePickedUp: boolean;
            vertical: string;
            verticalReason: string;
            company: string;
        };
        SentEmailDbRecord: {
            gmailMessageId: string;
            id: number;
            replied: number;
            vertical: string;
        };
        SentEmail: {
            id: string;
            threadId: string;
            from: string;
            to: string;
            recipientEmail: string;
            recipientName: string;
            subject: string;
            snippet: string;
            bodyPreview: string;
            date: string;
            timestamp: number;
            labelIds: string[];
            labelNames: string[];
            hasDoctrineLabel: boolean;
            matchedDoctrineLabels: string[];
            isSentByMe: boolean;
            detection: components["schemas"]["SentEmailDetection"];
            inDatabase: boolean;
            dbRecord?: components["schemas"]["SentEmailDbRecord"];
        };
        SentEmailsMeta: {
            total: number;
            withDoctrineLabel: number;
            inDatabase: number;
            wouldBePickedUp: number;
            doctrineLabelIds?: string[];
            doctrineLabels?: string[];
        };
        SentEmailsResponse: {
            emails: components["schemas"]["SentEmail"][];
            meta: components["schemas"]["SentEmailsMeta"];
        };
        ThreadMessage: {
            id: string;
            from: string;
            to: string;
            subject: string;
            date: string;
            timestamp: number;
            body: string;
            snippet: string;
            isFromMe: boolean;
            labelNames?: string[];
        };
        ThreadResponse: {
            threadId: string;
            messageCount: number;
            hasExternalReply: boolean;
            messages: components["schemas"]["ThreadMessage"][];
        };
        CancelResult: {
            cancelled: number;
        };
        StageTiming: {
            minDays: number;
            maxDays: number;
        };
        GmailAccount: {
            id: number;
            email: string;
            name: string;
            isConnected: boolean;
            stageTiming: components["schemas"]["StageTiming"][];
            sendDays: number[];
            sendHourStart: number;
            sendHourEnd: number;
            maxFollowups: number;
            doctrineLabel: string;
            testMode: boolean;
            requireApproval: boolean;
            createdAt?: string;
        };
        GmailAccountsResponse: {
            accounts: components["schemas"]["GmailAccount"][];
        };
        DisconnectResult: {
            success: boolean;
            email: string;
        };
        AccountSettingsUpdate: {
            stageTiming?: components["schemas"]["StageTiming"][];
            sendDays?: number[];
            sendHourStart?: number;
            sendHourEnd?: number;
            maxFollowups?: number;
            doctrineLabel?: string;
            testMode?: boolean;
            requireApproval?: boolean;
        };
        UpdateSettingsResult: {
            success: boolean;
            account?: components["schemas"]["GmailAccount"];
        };
        CampaignStats: {
            /** @enum {string} */
            type: "production" | "test";
            label: string;
            total: number;
            unreplied: number;
            paused: number;
            queued: number;
            sent: number;
            actionable: number;
        };
        CampaignUser: {
            id: number;
            email: string;
            name: string;
            test_mode: boolean;
            max_followups: number;
            doctrine_label: string;
            campaigns: components["schemas"]["CampaignStats"][];
        };
        CampaignStatus: {
            active: boolean;
            test_mode: boolean;
            queued_count: number;
            sent_count: number;
            unreplied_prospects: number;
            users?: components["schemas"]["CampaignUser"][];
        };
        CampaignLaunchRequest: {
            user_id?: number;
            max_stage?: number;
        };
        CampaignLaunchResult: {
            launched: boolean;
            queued: number;
            test_mode_enabled?: boolean;
            message: string;
        };
        CampaignStopResult: {
            stopped: boolean;
            cancelled_count: number;
            test_mode_disabled?: boolean;
            message: string;
        };
        ProspectPauseResult: {
            success: boolean;
            paused: boolean;
            cancelled_queued?: number;
        };
        ProspectResumeResult: {
            success: boolean;
            paused: boolean;
            queued_stage?: number | null;
            max_followups?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    getProspects: {
        parameters: {
            query?: {
                vertical?: string;
                replied?: string;
            };
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prospect groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProspectGroup"][];
                };
            };
        };
    };
    getFollowups: {
        parameters: {
            query?: {
                status?: string;
            };
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Follow-ups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Followup"][];
                };
            };
        };
    };
    triggerSync: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
        };
    };
    triggerProcess: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessResult"];
                };
            };
        };
    };
    queueFollowups: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueRequest"];
            };
        };
        responses: {
            /** @description Queue result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResult"];
                };
            };
        };
    };
    queueBatch: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueBatchRequest"];
            };
        };
        responses: {
            /** @description Queue result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResult"];
                };
            };
        };
    };
    getSentEmails: {
        parameters: {
            query?: {
                limit?: number;
                search?: string;
            };
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sent emails with detection metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentEmailsResponse"];
                };
            };
        };
    };
    getThread: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResponse"];
                };
            };
        };
    };
    startGmailAuth: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth authorization URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        authUrl: string;
                    };
                };
            };
        };
    };
    getGmailAccounts: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connected accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailAccountsResponse"];
                };
            };
        };
    };
    disconnectGmailAccount: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnect result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisconnectResult"];
                };
            };
        };
    };
    updateAccountSettings: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountSettingsUpdate"];
            };
        };
        responses: {
            /** @description Updated settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateSettingsResult"];
                };
            };
        };
    };
    cancelFollowups: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRequest"];
            };
        };
        responses: {
            /** @description Cancel result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResult"];
                };
            };
        };
    };
    pauseProspect: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prospect paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProspectPauseResult"];
                };
            };
        };
    };
    resumeProspect: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prospect resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProspectResumeResult"];
                };
            };
        };
    };
    getCampaignStatus: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignStatus"];
                };
            };
        };
    };
    queueCampaignFollowups: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    user_id?: string;
                    /** @enum {string} */
                    campaign_type: "production" | "test";
                };
            };
        };
        responses: {
            /** @description Queue result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        queued: number;
                        campaign_type?: string;
                        test_mode_enabled?: boolean;
                        message: string;
                    };
                };
            };
        };
    };
    launchCampaign: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CampaignLaunchRequest"];
            };
        };
        responses: {
            /** @description Campaign launch result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignLaunchResult"];
                };
            };
        };
    };
    stopCampaign: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign stop result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignStopResult"];
                };
            };
        };
    };
}
